# Site settings
title: xarisd.io
email: xaris.dimitriou@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal space of Haris Dimitriou (xarisd). A Thessaloniki/Greece based Ruby (mostly) developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xarisd.io" # the base hostname & protocol for your site
author: Haris Dimitriou (xarisd)
twitter_username: xarisd
github_username:  xarisd

# Global Settings
destination: _deploy

# Build settings
markdown: redcarpet
highlighter: true

